### ISSUE TITLE
revD Gerber files

### ISSUE THREAD

**Issue by xiphias256** [mbarszcz-pcb/c64-rf-modulator-replacement#1]
Hi!

Tried to upload your rev.D gerber files to PCBWay, and I got feedback that the files was not in the right format. Rev. C uploads and reviews fine.

Error message: "We need gerber file in fomat of RS-274x;"

**Comment by mbarszcz-pcb** [comment]
I think I know the problem.  Let me export some new ones and upload them..
They'll be listed as -pcbway.

**Comment by xiphias256** [comment]
Thanks!
PCBWay accepted the new file.
