### ISSUE TITLE
Swapped resistors in photo

### ISSUE THREAD

**Issue by MagerValp** [mbarszcz-pcb/c64-rf-modulator-replacement#2]
It looks like R4 and R5 have been swapped in the photo here:

https://github.com/mbarszcz-pcb/c64-rf-modulator-replacement/blob/master/images/photos/c64-rf-modulator-photo-inst.png

I was using the photo as a reference when assembling and it had me confused for a bit :)

**Comment by mbarszcz-pcb** [comment]
The example photo is from the earlier Rev B of the board.  The latest Rev D has the physical positions swapped, but the values still match their reference IDs.  When assembling the PCB please be sure to match the component values and reference IDs on the schematic with the reference IDs on the board's silkscreen.
